<?php
// Shared dashboard body. The caller must include its role header first.
function dashCount($sql){ global $conn; $r=$conn->query($sql); if(!$r)return 0; $x=$r->fetch_row(); return (int)($x[0]??0); }
$scope=currentSchoolScope(); $today=date('Y-m-d');
$where=schoolSql('s.school_scope') . ' AND ' . genderSql('s.st_gender');
$total=dashCount("SELECT COUNT(*) FROM students s WHERE $where AND s.st_statue='بەردەوام'");
$boys=dashCount("SELECT COUNT(*) FROM students s WHERE $where AND s.st_statue='بەردەوام' AND LOWER(s.st_gender)='male'");
$girls=dashCount("SELECT COUNT(*) FROM students s WHERE $where AND s.st_statue='بەردەوام' AND LOWER(s.st_gender)='female'");
$absent=dashCount("SELECT COUNT(DISTINCT a.student_id) FROM attendance a INNER JOIN students s ON s.id=a.student_id WHERE a.date='$today' AND a.status IN ('absent','permit') AND $where");
$teachers=dashCount("SELECT COUNT(*) FROM teachers t WHERE ".schoolSql('t.school_scope'));
$att=dashCount("SELECT COUNT(DISTINCT a.student_id) FROM attendance a INNER JOIN students s ON s.id=a.student_id WHERE a.date='$today' AND $where");
$cards=[];
$schools=getSchools(false); $cards=[]; foreach($schools as $school){ $sc=$school['school_code']; if($scope!=='ALL'&&$scope!==$sc)continue; $items=[]; foreach(getSchoolGrades($sc) as $g){ $gn=$conn->real_escape_string($g['grade_name']); $items[]=[$g['grade_name'],dashCount("SELECT COUNT(*) FROM students s WHERE s.school_scope='".$conn->real_escape_string($sc)."' AND s.st_class='$gn' AND s.st_statue='بەردەوام' AND ".genderSql('s.st_gender'))]; } $cards[]=[$sc,$school['school_name'],'Grades configured: '.count($items),$items]; }?>
<style>
.ud{padding:10px 5px 25px;color:#e2e8f0}.ud-hero{background:linear-gradient(135deg,#172b46,#0f172a);border:1px solid rgba(255,255,255,.08);border-radius:20px;padding:20px;display:flex;justify-content:space-between;align-items:center;gap:15px}.ud-hero h1{margin:0;font-size:25px}.ud-hero p{margin:5px 0 0;color:#94a3b8}.ud-scope{padding:8px 14px;border-radius:999px;background:rgba(56,189,248,.12);color:#7dd3fc;font-weight:700}.ud-stats{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin:15px 0}.ud-stat{background:#111f33;border:1px solid rgba(255,255,255,.07);border-radius:16px;padding:15px}.ud-stat small{color:#94a3b8}.ud-stat b{font-size:25px;display:block;margin-top:7px}.ud-stat.alert b{color:#fbbf24}.ud-title{font-size:18px;font-weight:800;margin:20px 0 10px}.ud-schools{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:14px}.ud-school{background:#111f33;border:1px solid rgba(255,255,255,.07);border-radius:18px;padding:16px}.ud-school h3{margin:0}.ud-school p{color:#94a3b8;margin:3px 0 14px}.ud-grades{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.ud-grade{background:#17263b;border-radius:10px;padding:10px;text-align:center}.ud-grade span{display:block;color:#94a3b8;font-size:12px}.ud-grade b{font-size:19px}.ud-links{display:flex;gap:10px;flex-wrap:wrap;margin-top:15px}.ud-links a{background:#111f33;border:1px solid rgba(255,255,255,.07);border-radius:10px;padding:10px 14px;color:#e2e8f0;text-decoration:none}.ud-links a:hover{background:#1e293b}@media(max-width:1100px){.ud-stats{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.ud-stats{grid-template-columns:repeat(2,1fr)}.ud-grades{grid-template-columns:repeat(2,1fr)}.ud-hero{align-items:flex-start;flex-direction:column}}
</style>
<div class="ud">
<div class="ud-hero"><div><h1>Unified School Dashboard</h1><p>Live overview for the school area assigned to this account.</p></div><div class="ud-scope"><?php echo htmlspecialchars($scope); ?></div></div>
<div class="ud-stats"><div class="ud-stat"><small>Active Students</small><b><?php echo number_format($total); ?></b></div><div class="ud-stat"><small>Boys</small><b><?php echo number_format($boys); ?></b></div><div class="ud-stat"><small>Girls</small><b><?php echo number_format($girls); ?></b></div><div class="ud-stat"><small>Teachers</small><b><?php echo number_format($teachers); ?></b></div><div class="ud-stat"><small>Attendance Today</small><b><?php echo number_format($att); ?></b></div><div class="ud-stat alert"><small>Absent / Permit Today</small><b><?php echo number_format($absent); ?></b></div></div>
<div class="ud-title">School Breakdown</div><div class="ud-schools"><?php foreach($cards as $c){ ?><div class="ud-school"><h3><?php echo $c[1]; ?></h3><p><?php echo $c[2]; ?></p><div class="ud-grades"><?php foreach($c[3] as $g){ ?><div class="ud-grade"><span><?php echo htmlspecialchars($g[0]); ?></span><b><?php echo number_format($g[1]); ?></b></div><?php } ?></div></div><?php } ?></div>
<div class="ud-links"><a href="manager.php">Student Search</a><a href="today_att.php">Today Attendance</a><a href="lozanstaaffpage.php">Teacher Staff</a></div>
</div>
